version: '3.8'

services:
  n5db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: n5db
    environment:
        SA_PASSWORD: "ASDF1234"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "testtopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: "9092"
    volumes:
      - c:/docker.sock:/var/run/docker.sock  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    expose:
      - 9200
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=DkIedPPSCb
    ports:
      - 9200:9200